sudo: false
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

  # command to install dependencies
install:
  - pip install .

# command to run tests
# online tests uses TL connection, defined in 
#  TESTLINK_API_PYTHON_DEVKEY and TESTLINK_API_PYTHON_SERVER_URL
#  see https://travis-ci.org/USER/TestLink-API-Python-client/settings/env_vars
# suggestion: use TL demo project with user pyTLapi, see tox.ini
script: 
  - py.test test/utest-offline
  - if [[ $TESTLINK_API_PYTHON_SERVER_URL ]]; then py.test test/utest-online; fi
# see known problem:  countTestCasesTS should handle the sufficient right errors #62   
#  - if [[ $TESTLINK_API_PYTHON_SERVER_URL && $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python example/TestLinkExample.py; fi
